#!/usr/bin/ruby

# This software is public domain and has no express or implied warranty.

def usage(*args)
	print *args
	print "\n"
	print "Set up the firewall on a Linux server. If no services are specified only SSH is allowed. Ping flood protection is enabled unless --drop-ping is specified.\n"
	print "\n"
	print "Usage: iptabs.pl [ --help ] [ --enable-tcp SERVICELIST ] [ --enable-udp UDPSERVICELIST ] [ OPTIONS ]\n"
	print "\n"
	print "Options:\n"
	print "--help\n"
	print "\tDisplay this helpful message.\n"
	print "--enable-tcp SERVICELIST\n"
	print "\tSERVICELIST is a comma separated list of services, e.g. \"ssh,www,https,pop3\"\n"
	print "\tPorts can be specified numerically, e.g. \"80,443\"\n"
	print "\tRanges of ports can be specified numerically, e.g. \"5500:5599\"\n"
	print "\tRanges of ports can be combined, e.g. \"5500:5599,6000:6100,8080\"\n"
	print "--enable-udp UDPSERVICELIST\n"
	print "\tUDPSERVICELIST works like SERVICELIST above for UDP ports.\n"
	print "--interface INTERFACE\n"
	print "\tSpecify an interface for following rules. Use --interface any to specify any interface.\n"
	print "--sshguard\n"
	print "\tEnable SSHGuard protection. SSHGuard should be installed.\n"
	print "--fwknop\n"
	print "\tEnable fwknop server support.\n"
	print "--forward\n"
	print "\tEnable forwarding. Should only be used on a router.\n"
	print "--drop-ipv6\n"
	print "\tDrop all IPv6 packets.\n"
	print "--drop-ping\n"
	print "\tDrop all ICMP PING packets.\n"
	print "--no-drop-null\n"
	print "\tDo not drop all NULL packets.\n"
	print "--no-drop-fragments\n"
	print "\tDo not drop all fragments.\n"
	print "--no-syn-protect\n"
	print "\tDo not use SYN protection.\n"
	print "--no-drop-xmas\n"
	print "\tDo not drop XMAS packets.\n"
	print "--no-drop-finscans\n"
	print "\tDo not drop FIN scans.\n"
	print "--knock DEST:FIRST:SECOND:THIRD:FOURTH\n"
	print "\tSetup TCP port knocking for the specified service. DEST is the service, and the knock ports are given in order.\n"
	print "--no-knock-log\n"
	print "\tDo not log port knock attempts. Use if PSAD is used on the host.\n"
	print "--dump-to\n"
	print "\tDump the netfilter commands to the given file instead of executing them.\n"
	print "--by-spec\n"
	print "\tAllow the ports, protocol, and network/host specified by the argument string, e.g. 192.168.1.0/24:tcp:22,80,443,5900-5999\n"
	print "--clear\n"
	print "\tJust clear the existing firewall rules and exit.\n"
	print "--trusted-iface IFACE[,IFACEx ...]\n"
	print "\tMark the interface[s] as trusted, permitting all traffic. Loopback is automatically trusted, so do not add it with this option.\n"
	print "--drop\n"
	print "\tSpecify hosts or networks that should be dropped. Use multiple times, with IPv4 or IPv6\n"
	print "--throttle NUM\n"
	print "\tProtect against DOS. NUM is the limit per minute for new connections. Bursts to 4x.\n"
	print "--est-throttle NUM\n"
	print "\tProtect against DOS. NUM is the limit per second of established connections. Bursts to 2x.\n"
	print "--blacklist SPEC[,SPEC...]\n"
	print "\tBlacklist hosts and/or networks. Separate multiples with commas.\n"
	print "--blacklist-file FILENAME\n"
	print "\tBlacklist hosts and/or networks listed in FILENAME\n"
	print "--badguy SPEC[,SPEC...]\n"
	print "\tBlock hosts and/or networks with existing firewall. Separate multiples with commas.\n"
	print "--badguy-file FILENAME\n"
	print "\tBlock hosts and/or networks from a file, without reloading firewall.\n"
	print "--file FILENAME\n"
	print "\tRead firewall commands from FILENAME\n"
	print "\n"
	exit 1
end

class GlobalData
	attr_accessor :sshguard
	attr_accessor :fwknop
	attr_accessor :forward
	attr_accessor :drop_ipv6
	attr_accessor :drop_ping
	attr_accessor :no_drop_null
	attr_accessor :no_drop_fragments
	attr_accessor :no_syn_protect
	attr_accessor :no_drop_xmas
	attr_accessor :no_drop_finscans
	attr_accessor :clear_only
	attr_accessor :tcp
	attr_accessor :udp
	attr_accessor :trusted_iface
	attr_accessor :by_spec
	attr_accessor :blacklist
	attr_accessor :knock
	attr_accessor :no_knock_log
	attr_accessor :interface
	attr_accessor :dump_to
	attr_accessor :dos_protect
	attr_accessor :dos_conn_protect

	def initialize
		# Booleans
		@sshguard = false
		@fwknop = false
		@forward = false
		@drop_ipv6 = false
		@drop_ping = false
		@no_drop_null = false
		@no_drop_fragments = false
		@no_syn_protect = false
		@no_drop_xmas = false
		@no_drop_finscans = false
		@clear_only = false
		@no_knock_log = false

		# Arrays
		@tcp = Array.new
		@udp = Array.new
		@trusted_iface = Array.new
		@by_spec = Array.new
		@blacklist = Array.new
		@knock = Array.new

		# Strings
		@interface = "any"
		@dump_to = nil
	end
end

class Rule
	def initialize(conf)
		@config = conf
		if @config.dump_to
			@file = File.new @config.dump_to, "w"
			@file.write "#!/bin/sh\n"
		end
		return self
	end

	def add_ipv4(what)
		return output "iptables", what
	end

	def add_ipv6(what)
		return self if @config.drop_ipv6
		return output "ip6tables", what
	end

	def add(what)
		return add_ipv4(what).add_ipv6(what)
	end

	def service_enable(proto, list)
		iface, service_string = list.split "#"
        dos = ""
        dos = " -m limit --limit #{@config.dos_protect}/minute --limit-burst #{Integer(@config.dos_protect) * 2}" unless @config.dos_protect.nil?
		service_string.split(",").each do |dport|
            portspec = dport[/[a-zA-Z]/] ? dport : dport.sub(/-/,':')
			add "-A INPUT #{((!iface[/^any$/]) ? "-i " + iface : "")} -p #{proto} --dport #{portspec}#{dos} -j ACCEPT"
		end
	end

	private

	def output(which, what)
		if @file
			@file.write which + " " + what + "\n"
		else
			system which + " " + what
		end
		return self
	end

end

def block_badguy(toblock)
    if toblock[/:/]
        system "ip6tables -A blacklist -s #{toblock} -j DROP"
    else
        system "iptables -A blacklist -s #{toblock} -j DROP"
    end
    puts "Blacklisted #{toblock}"
end

def process_arguments(cfg, args)
    while args.size > 0
        cmd = args.shift.sub(/^--/, '')

        if cmd[/^enable-tcp$/]
            usage "option enable-tcp needs an argument\n" if args.size < 1
            cfg.tcp.push cfg.interface + "#" + args.shift
        elsif cmd[/^enable-udp$/]
            usage "option enable-udp needs an argument\n" if args.size < 1
            cfg.udp.push cfg.interface + "#" + args.shift
        elsif cmd[/^interface$/]
            usage "option interface needs an argument\n" if args.size < 1
            cfg.interface = args.shift
        elsif cmd[/^sshguard$/]
            cfg.sshguard = true
        elsif cmd[/^fwknop$/]
            cfg.fwknop = true
        elsif cmd[/^forward$/]
            cfg.forward = true
        elsif cmd[/^drop-ipv6$/]
            cfg.drop_ipv6 = true
        elsif cmd[/^drop-ping$/]
            cfg.drop_ping = true
        elsif cmd[/^no-drop-null$/]
            cfg.no_drop_null = true
        elsif cmd[/^no-drop-fragments$/]
            cfg.no_drop_fragments = true
        elsif cmd[/^no-syn-protect$/]
            cfg.no_syn_protect = true
        elsif cmd[/^no-drop-xmas$/]
            cfg.no_drop_xmas = true
        elsif cmd[/^no-drop-finscans$/]
            cfg.no_drop_finscans = true
        elsif cmd[/^knock$/]
            usage "option knock needs an argument\n" if args.size < 1
            cfg.knock.push args.shift
        elsif cmd[/^no-knock-log$/]
            cfg.no_knock_log = true
        elsif cmd[/^dump-to$/]
            usage "option dump-to needs an argument\n" if args.size < 1
            cfg.dump_to = args.shift
        elsif cmd[/^by-spec$/]
            usage "option by-spec needs an argument\n" if args.size < 1
            usage "Specification is incorrect\n" unless args[0][/^[0-9.]+\/[0-9]+:[tu][dc]p:[0-9,-]+$/]
            cfg.by_spec.push args.shift.gsub(/:/, ';').gsub(/-/, ':')
        elsif cmd[/^clear$/]
            cfg.clear_only = true
        elsif cmd[/^trusted-iface$/]
            usage "option trusted-iface needs an argument\n" if args.size < 1
            cfg.trusted_iface.push args.shift
        elsif cmd[/^throttle$/]
            usage "option throttle needs a numeric argument\n" if args.size < 1 || !args[0][/^[0-9]+$/]
            cfg.dos_conn_protect = args.shift
        elsif cmd[/^est-throttle$/]
            usage "option est-throttle needs a numeric argument\n" if args.size < 1 || !args[0][/^[0-9]+$/]
            cfg.dos_protect = args.shift
        elsif cmd[/^blacklist$/]
            usage "option blacklist needs an argument\n" if args.size < 1
            args.shift.split(/,/).each { |toblock| cfg.blacklist.push toblock }
        elsif cmd[/^blacklist-file$/]
            usage "option blacklist-file needs an argument\n" if args.size < 1
            if !File::exists?(args[0])
                usage "File #{args[0]} does not exist."
            end
            File.open(args.shift, "r") do |infile|
                while (line = infile.gets)
                    line.chomp.split(/,/).each { |badguy| cfg.blacklist.push badguy } if line.size > 1 && !line[/^#/]
                end
            end
        elsif cmd[/^badguy$/]
            usage "option badguy needs an argument\n" if args.size < 1
            args.shift.split(/,/).each { |toblock| block_badguy toblock }
            exit 0
        elsif cmd[/^badguy-file$/]
            usage "option badguy-file needs an argument\n" if args.size < 1
            if !File::exists?(args[0])
                usage "File #{args[0]} does not exist."
            end
            File.open(args.shift, "r") do |infile|
                while (line = infile.gets)
                    line.chomp.split(/,/).each { |toblock| block_badguy toblock } if line.size > 1 && !line[/^#/]
                end
            end
            exit 0
        elsif cmd[/^file$/]
            usage "option file needs an argument\n" if args.size < 1
            if !File::exists?(args[0])
                usage "File #{args[0]} does not exist."
            end
            fileargs = Array.new
            File.open(args.shift, "r") do |infile|
                while (line = infile.gets)
                    line.chomp.split(/\s+/).each { |to_process| fileargs.push to_process } if line.size > 1 && !line[/^#/]
                end
            end
            process_arguments cfg, fileargs
        else
            usage "Unrecognized option #{cmd}\n\n"
        end
    end
end

#-------------#
# Entry point #
#-------------#

config = GlobalData.new

process_arguments config, ARGV

rule = Rule.new(config)

# Clear existing tables
rule.add("-F").add("-P INPUT ACCEPT").add("-P OUTPUT ACCEPT")
IO.popen("iptables -S") do |f|
    f.each { |line| rule.add "-X #{line.sub(/^-N\s+/, "").chomp}" if line[/^-N\s+/] }
end if config.dump_to.nil?

exit 0 if config.clear_only

# Clear out existing tables, unless writing to a dump file
IO.foreach("|iptables -S") do |line|
	rule.add("iptables -X #{line[3..-2]}\n").add("iptables -X #{line[3..-2]}\n") if line[/^-N\s/]
end unless config.dump_to

unless config.no_drop_fragments
	# IPv4 fragment drop is pretty simple
	rule.add_ipv4 "-A INPUT -f -j DROP"

	# IPv6 fragment drop is a little more involved
	["fragfirst", "fragmore", "fraglast"].each do |fragspec|
		rule.add_ipv6 "-A INPUT -m frag --#{fragspec} -j DROP"
	end
end

# Trusted interfaces
config.trusted_iface.unshift "lo"
config.trusted_iface.each { |iface| rule.add "-A INPUT -i #{iface} -j ACCEPT" }

rule.add "-N blacklist"
rule.add "-A INPUT -j blacklist"
rule.add "-A OUTPUT -j blacklist"

config.blacklist.each do |drop|
    if drop[/:/]
        rule.add_ipv6 "-A blacklist -s #{drop} -j DROP"
    else
        rule.add_ipv4 "-A blacklist -s #{drop} -j DROP"
    end
end

# Protect from ping floods
rule.add "-A INPUT -p icmp -m limit --limit 2/second --limit-burst 3 -j ACCEPT" unless config.drop_ping

# SYN Protection
rule.add("-A INPUT -p tcp ! --syn -m state --state NEW  -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix \"Drop Syn\"").add("-A INPUT -p tcp ! --syn -m state --state NEW -j DROP") unless config.no_syn_protect

# XMAS packet scan protection
rule.add("-A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix \"XMAS Packets\"").add("-A INPUT -p tcp --tcp-flags ALL ALL -j DROP") unless config.no_drop_xmas

# Detect FIN packet scans
rule.add("-A INPUT -p tcp --tcp-flags FIN,ACK FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix \"FIN Packet Scan\"").add("-A INPUT -p tcp --tcp-flags FIN,ACK FIN -j DROP") unless config.no_drop_finscans

# Drop NULL packets
rule.add("-A INPUT -p tcp --tcp-flags ALL NONE -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix \"NULL Packets\"").add("-A INPUT -p tcp --tcp-flags ALL NONE -j DROP") unless config.no_drop_null

# Protect established connections from DOS/DDOS
dos = ""
dos = " -m limit --limit #{config.dos_conn_protect}/second --limit-burst #{Integer(config.dos_conn_protect) * 4}" if config.dos_conn_protect != nil

# Accept anything we established
rule.add "-A INPUT -m state --state ESTABLISHED,RELATED#{dos} -j ACCEPT"

# Knocking
config.knock.each do |knockline|
	endport, first, second, third, fourth = knockline.split ":"

	(2..4).each do |d|
		rule.add "-N #{endport}-INTO-PHASE#{d}"
		rule.add "-A #{endport}-INTO-PHASE#{d} -m recent --name #{endport}-PHASE#{d - 1} --remove"
		rule.add "-A #{endport}-INTO-PHASE#{d} -m recent --name #{endport}-PHASE#{d} --set"
		rule.add "-A #{endport}-INTO-PHASE#{d} -j LOG --log-prefix \"INTO #{endport}-PHASE#{d}: \"" unless config.no_knock_log
	end

	rule.add "-A INPUT -m recent --update --name #{endport}-PHASE1"

	rule.add "-A INPUT -p tcp --dport #{first} -m recent --set --name #{endport}-PHASE1"

	rule.add "-A INPUT -p tcp --dport #{second} -m recent --rcheck --name #{endport}-PHASE1 -j #{endport}-INTO-PHASE2"
	rule.add "-A INPUT -p tcp --dport #{third} -m recent --rcheck --name #{endport}-PHASE2 -j #{endport}-INTO-PHASE3"
	rule.add "-A INPUT -p tcp --dport #{fourth} -m recent --rcheck --name #{endport}-PHASE3 -j #{endport}-INTO-PHASE4"

	rule.add "-A INPUT -p tcp --syn --dport #{endport} -m recent --rcheck --seconds 5 --name #{endport}-PHASE4 -j LOG --log-prefix \"KNOCK UNLOCK: \"" unless config.no_knock_log
	rule.add "-A INPUT -p tcp --syn --dport #{endport} -m recent --rcheck --seconds 5 --name #{endport}-PHASE4 -j ACCEPT"
end

# SSHGuard
rule.add("-N sshguard").add("-A INPUT -j sshguard").add("-A OUTPUT -j sshguard") if config.sshguard
rule.add("-N FWKNOP_INPUT").add("-A INPUT -j FWKNOP_INPUT") if config.fwknop

# By spec
config.by_spec.each do |specline|
	nh, protocol, ports = specline.split ";"
	ports.split(",").each { |p| rule.add_ipv4 "-A INPUT -p #{protocol} -s #{nh} --dport #{p} -j ACCEPT" }
end

# TCP services
config.tcp.each { |service| rule.service_enable "tcp", service }

# UDP Sevices
config.udp.each { |service| rule.service_enable "udp", service }

# Logging for PSAD and drop everything else
rule.add("-A INPUT -j LOG").add("-A FORWARD -j LOG").add("-A INPUT -j DROP")

exit 0
